### PR TITLE
Changes required to build against iRODS 4.3.x

### PR DESCRIPTION
**Pull request by jasoncoposky**
Massaged some CMake.

### CODE REVIEW

**Comment by korydraughn** [comment]
Let's use issue number 3 for these commits.

**Comment by korydraughn** [comment]
Does it compile and run?
Have the tests been run? Do they pass? _(Not a blocker IMO)_

I think we get this merged so we can review the implementation as a whole and create issues. I don't think we need to block this because the code has never been released.

@trel @alanking Thoughts?

**Comment by trel** [comment]
agreed.  no blockers.  we can always add more before a release.

**Comment by korydraughn** [comment]
Ok. I'll close the issue number and we can proceed with merging.

**Review by korydraughn — APPROVED** [review]

**Comment by alanking** [comment]
Agreed.

Are we squashing and linking to #3? Or just merging?

**Comment by korydraughn** [comment]
Let's just merge it.

**Review by alanking — APPROVED** [review]

**Comment by trel** [comment]
bulid!

**Pull request merged**
